-- CREATE SEQUENCES

    -- AUTHOR
    CREATE SEQUENCE AUTHOR_SEQUENCE
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

    -- CATEGORY
    CREATE SEQUENCE CATEGORY_SEQUENCE
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
    
    -- BOOK
    CREATE SEQUENCE BOOK_SEQUENCE
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
---------------------------------------------

-- CREATE TABLES

    -- AUTHOR
    CREATE TABLE AUTHOR
    (
    ID              NUMBER DEFAULT AUTHOR_SEQUENCE.NEXTVAL,
    NAME            VARCHAR2(50)  NOT NULL,
    BIRTHDAY        DATE,
    PHOTO           VARCHAR2(255),
    STATUS          CHAR(1) DEFAULT 'A',
    CREATION_DATE   DATE DEFAULT SYSDATE
    );
    
    -- CATEGORY
     CREATE TABLE CATEGORY
    (
    ID                         NUMBER DEFAULT CATEGORY_SEQUENCE.NEXTVAL,
    NAME                       VARCHAR2(50)  NOT NULL,
    STATUS                     CHAR(1) DEFAULT 'A',
    CREATION_DATE              DATE DEFAULT SYSDATE
    );
    
    -- BOOK
     CREATE TABLE BOOK
    (
    ID                       NUMBER DEFAULT BOOK_SEQUENCE.NEXTVAL,
    PUBLICATION_DATE         VARCHAR2(50)  NOT NULL,
    PRICE                    NUMBER(8,3),
    TITLE                    VARCHAR2(50),
    DESCRIPTION              VARCHAR2(255),
    PHOTO                    VARCHAR2(255),
    STATUS                   CHAR(1) DEFAULT 'A',
    CATEGORY_ID              NUMBER,
    AUTHOR_ID                NUMBER,
    CREATION_DATE            DATE DEFAULT SYSDATE
    );
---------------------------------------------

-- ADD CONSTRAINTS
   -- AUTHOR
   ALTER TABLE AUTHOR ADD CONSTRAINT PK_AUTHOR_ID PRIMARY KEY (ID);
   
   -- CATEGORY
   ALTER TABLE CATEGORY ADD CONSTRAINT PK_CATEGORY_ID PRIMARY KEY (ID);
   
   -- BOOK
   ALTER TABLE BOOK ADD CONSTRAINT PK_BOOK_ID PRIMARY KEY (ID);
   ALTER TABLE BOOK ADD CONSTRAINT FK_CATEGORY_ID FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(ID);
   ALTER TABLE BOOK ADD CONSTRAINT FK_AUTHOR_ID FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR(ID);

---------------------------------------------
-- ADD COMMENTS

    -- AUTHOR
    COMMENT ON COLUMN AUTHOR.ID IS 'PRIMARY KEY OF THE AUTHORS TABLE';
    COMMENT ON COLUMN AUTHOR.NAME IS 'NAME OF THE AUTHOR';
    COMMENT ON COLUMN AUTHOR.BIRTHDAY IS 'BIRTHDAY OF THE AUTHOR';
    COMMENT ON COLUMN AUTHOR.PHOTO IS 'PHOTO OF THE AUTHOR';
    COMMENT ON COLUMN AUTHOR.STATUS IS 'DATA STATUS I-INACTIVE / A-ACTIVE';
    COMMENT ON COLUMN AUTHOR.CREATION_DATE IS 'DATE ON THE RECORD WAS CREATED';
    
    -- CATEGORY
    COMMENT ON COLUMN CATEGORY.ID IS 'PRIMARY KEY OF THE CATEGORY TABLE';
    COMMENT ON COLUMN CATEGORY.NAME IS 'NAME OF THE CATEGORY';
    COMMENT ON COLUMN CATEGORY.STATUS IS 'DATA STATUS I-INACTIVE / A-ACTIVE';
    COMMENT ON COLUMN CATEGORY.CREATION_DATE IS 'DATE ON THE RECORD WAS CREATED';
    
    -- BOOK
    COMMENT ON COLUMN BOOK.ID IS 'PRIMARY KEY OF THE BOOK TABLE';
    COMMENT ON COLUMN BOOK.PUBLICATION_DATE IS 'DATE OF PUBLICATION BOOK';
    COMMENT ON COLUMN BOOK.PRICE IS 'PRICE OF BOOK';
    COMMENT ON COLUMN BOOK.TITLE IS 'TITLE OF BOOK';
    COMMENT ON COLUMN BOOK.DESCRIPTION IS 'DESCRIPTION OF BOOK';
    COMMENT ON COLUMN BOOK.PHOTO IS 'IIMAGE THAT REPRESENTS THE BOOK';
    COMMENT ON COLUMN BOOK.STATUS IS 'DATA STATUS I-INACTIVE / A-ACTIVE';
    COMMENT ON COLUMN BOOK.CATEGORY_ID IS 'FIELD THAT RELATES THE CATEGORY TABLE WITH THE BOOK TABLE';
    COMMENT ON COLUMN BOOK.AUTHOR_ID IS 'FIELD THAT RELATES THE AUTHOR TABLE WITH THE BOOK TABLE';
    COMMENT ON COLUMN BOOK.CREATION_DATE IS 'DATE ON THE RECORD WAS CREATED';
    
---------------------------------------------
-- DROP TABLES
   DROP TABLE BOOK;
   DROP TABLE AUTHOR;
   DROP TABLE CATEGORY;
