
-- INSERT AUTHORS
INSERT INTO USER_BOOK.AUTHOR (NAME, BIRTHDAY, PHOTO) 
VALUES ('Gabriel García Márquez', TO_DATE('06-03-1927', 'DD-MM-YYYY'), 'image.jpg');
INSERT INTO AUTHOR (NAME, BIRTHDAY, PHOTO) 
VALUES ('Isabel Allende', TO_DATE('02-08-1942', 'DD-MM-YYYY'), 'image.jpg');
INSERT INTO AUTHOR (NAME, BIRTHDAY, PHOTO) 
VALUES ('Pablo Neruda', TO_DATE('12-07-1904', 'DD-MM-YYYY'), 'image.jpg');
INSERT INTO AUTHOR (NAME, BIRTHDAY, PHOTO) 
VALUES ('Jorge Luis Borges', TO_DATE('24-08-1899', 'DD-MM-YYYY'), 'image.jpg');
INSERT INTO AUTHOR (NAME, BIRTHDAY, PHOTO) 
VALUES ('Mario Vargas Llosa', TO_DATE('28-03-1936', 'DD-MM-YYYY'), 'image.jpg');
INSERT INTO AUTHOR (NAME, BIRTHDAY, PHOTO) 
VALUES ('Julio Cortázar', TO_DATE('26-08-1914', 'DD-MM-YYYY'), 'image.jpg');
INSERT INTO AUTHOR (NAME, BIRTHDAY, PHOTO) 
VALUES ('Gustavo Adolfo Bécquer', TO_DATE('17-02-1836', 'DD-MM-YYYY'), 'image.jpg');
INSERT INTO AUTHOR (NAME, BIRTHDAY, PHOTO) 
VALUES ('Miguel de Cervantes', TO_DATE('29-09-1547', 'DD-MM-YYYY'), 'image.jpg');
INSERT INTO AUTHOR (NAME, BIRTHDAY, PHOTO) 
VALUES ('William Shakespeare', TO_DATE('26-04-1564', 'DD-MM-YYYY'), 'image.jpg');
INSERT INTO AUTHOR (NAME, BIRTHDAY, PHOTO) 
VALUES ('Edgar Allan Poe', TO_DATE('19-01-1809', 'DD-MM-YYYY'), 'image.jpg');


-- INSERT CATEGORY
INSERT INTO CATEGORY (NAME) VALUES ('Ciencia ficción');
INSERT INTO CATEGORY (NAME) VALUES ('Novela histórica');
INSERT INTO CATEGORY (NAME) VALUES ('Poesía');
INSERT INTO CATEGORY (NAME) VALUES ('Misterio');
INSERT INTO CATEGORY (NAME) VALUES ('Romance');
INSERT INTO CATEGORY (NAME) VALUES ('Fantasía');
INSERT INTO CATEGORY (NAME) VALUES ('Aventura');
INSERT INTO CATEGORY (NAME) VALUES ('Biografía');
INSERT INTO CATEGORY (NAME) VALUES ('Ensayo');
INSERT INTO CATEGORY (NAME) VALUES ('Cuentos');

-- INSERT BOOk
INSERT INTO BOOK (PUBLICATION_DATE, PRICE, TITLE, DESCRIPTION, CATEGORY_ID, AUTHOR_ID)
VALUES ('2021-06-01', 25.99, 'El amor en los tiempos del cólera', 'La obra maestra de Gabriel García Márquez', 1, 1);
INSERT INTO BOOK (PUBLICATION_DATE, PRICE, TITLE, DESCRIPTION, CATEGORY_ID, AUTHOR_ID)
VALUES ('2018-10-15', 19.99, 'La chica del tren', 'Una novela llena de suspense', 2, 2);
INSERT INTO BOOK (PUBLICATION_DATE, PRICE, TITLE, DESCRIPTION, CATEGORY_ID, AUTHOR_ID)
VALUES ('2020-03-21', 17.50, '1984', 'Una obra maestra de George Orwell', 3, 3);
INSERT INTO BOOK (PUBLICATION_DATE, PRICE, TITLE, DESCRIPTION, CATEGORY_ID, AUTHOR_ID)
VALUES ('2015-07-12', 29.99, 'Los juegos del hambre', 'Una emocionante saga de Suzanne Collins', 4, 4);
INSERT INTO BOOK (PUBLICATION_DATE, PRICE, TITLE, DESCRIPTION, CATEGORY_ID, AUTHOR_ID)
VALUES ('2019-02-04', 12.75, 'Crónica de una muerte anunciada', 'Una obra imprescindible de Gabriel García Márquez', 1, 1);
INSERT INTO BOOK (PUBLICATION_DATE, PRICE, TITLE, DESCRIPTION, CATEGORY_ID, AUTHOR_ID)
VALUES ('2022-01-10', 21.50, 'La sombra del viento', 'Un libro lleno de misterio y aventuras', 5, 5);
INSERT INTO BOOK (PUBLICATION_DATE, PRICE, TITLE, DESCRIPTION, CATEGORY_ID, AUTHOR_ID)
VALUES ('2017-08-08', 18.99, 'El psicoanalista', 'Una novela psicológica de John Katzenbach', 6, 6);
INSERT INTO BOOK (PUBLICATION_DATE, PRICE, TITLE, DESCRIPTION, CATEGORY_ID, AUTHOR_ID)
VALUES ('2016-05-20', 14.25, 'Harry Potter y la piedra filosofal', 'La primera novela de la saga de Harry Potter', 7, 7);
INSERT INTO BOOK (PUBLICATION_DATE, PRICE, TITLE, DESCRIPTION, CATEGORY_ID, AUTHOR_ID)
VALUES ('2021-11-02', 26.50, 'La reina del sur', 'Una novela de Arturo Pérez-Reverte', 8, 8);
INSERT INTO BOOK (PUBLICATION_DATE, PRICE, TITLE, DESCRIPTION, CATEGORY_ID, AUTHOR_ID)
VALUES ('2014-12-17', 16.99, 'Cien años de soledad', 'Una obra cumbre de Gabriel García Márquez', 1, 1);

SELECT * FROM CATEGORY;
SELECT * FROM AUTHOR;
SELECT * FROM BOOK;
